from uv.bsbetreuung.lib.pdfgen import createpdf
import tempfile

ma = {'mitarbeiter': '35,0'}
gb = {'bgruppe': 'II', 'gb_step0': '', 'gb_step1': 'D', 'gb_step2': '35', 'gb_step3': '35.2', 'gb_steps': 3, 'wzcodenr': '35.2', 'wzcodetext': u'Gasversorgung', 'min': '10,5', 'gb_data': '52,5'}
sb = {'sbsum': 15.247499999999999, 'steps': ['1.1', '1.2', '1.3', '1.4', '1.5', '1.8'], 'sbvalues': ['moegliche-gesundheitsschaeden', 'fachliche-komplexitaet', 'anteil-der-betroffenen-beschaeftigten', 'haeufigkeit-der-leistungserbringung'], 'stepdata': {'1.4': {'stepvalue': 1.75, 'commentdata': [], 'valuedata': [], 'data': {'mybool': u'ja'}, 'alt': 'Der zeitliche Umfang der arbeitsmedizinischen Vorsorge kann mit dieser Handlungshilfe nicht abgesch\xc3\xa4tzt werden. Der konkrete Bedarf und die erforderliche Zeit f\xc3\xbcr die arbeitsmedizinische Vorsorge ist betriebsindividuell durch den Betriebsarzt zu ermitteln.'}, '1.5': {'stepvalue': 2.5724999999999998, 'commentdata': [], 'valuedata': ['haeufigkeit-der-leistungserbringung', 'fachliche-komplexitaet', 'anteil-der-betroffenen-beschaeftigten', 'moegliche-gesundheitsschaeden'], 'data': {'moegliche-gesundheitsschaeden': u'1.4', 'mybool': u'ja', 'fachliche-komplexitaet': u'1.5', 'anteil-der-betroffenen-beschaeftigten': u'1', 'haeufigkeit-der-leistungserbringung': u'0.7'}, 'alt': ''}, '1.1': {'stepvalue': 1.0, 'commentdata': [], 'valuedata': ['anteil-der-betroffenen-beschaeftigten', 'moegliche-gesundheitsschaeden', 'haeufigkeit-der-leistungserbringung', 'fachliche-komplexitaet'], 'data': {'moegliche-gesundheitsschaeden': u'0.8', 'mybool': u'ja', 'fachliche-komplexitaet': u'1.0', 'anteil-der-betroffenen-beschaeftigten': u'1', 'haeufigkeit-der-leistungserbringung': u'0.7'}, 'alt': ''}, '1.2': {'stepvalue': 1.0, 'commentdata': [], 'valuedata': ['fachliche-komplexitaet', 'anteil-der-betroffenen-beschaeftigten', 'moegliche-gesundheitsschaeden', 'haeufigkeit-der-leistungserbringung'], 'data': {'moegliche-gesundheitsschaeden': u'1.4', 'mybool': u'ja', 'fachliche-komplexitaet': u'1.0', 'anteil-der-betroffenen-beschaeftigten': u'0.5', 'haeufigkeit-der-leistungserbringung': u'0.7'}, 'alt': ''}, '1.3': {'stepvalue': 5.25, 'commentdata': [], 'valuedata': ['anteil-der-betroffenen-beschaeftigten', 'moegliche-gesundheitsschaeden', 'haeufigkeit-der-leistungserbringung', 'fachliche-komplexitaet'], 'data': {'moegliche-gesundheitsschaeden': u'2', 'mybool': u'ja', 'fachliche-komplexitaet': u'1.5', 'anteil-der-betroffenen-beschaeftigten': u'1', 'haeufigkeit-der-leistungserbringung': u'1.0'}, 'alt': ''}, '1.8': {'stepvalue': 3.6749999999999998, 'commentdata': [], 'valuedata': ['anteil-der-betroffenen-beschaeftigten', 'moegliche-gesundheitsschaeden', 'haeufigkeit-der-leistungserbringung', 'fachliche-komplexitaet'], 'data': {'moegliche-gesundheitsschaeden': u'1.4', 'mybool': u'ja', 'fachliche-komplexitaet': u'1.5', 'anteil-der-betroffenen-beschaeftigten': u'1', 'haeufigkeit-der-leistungserbringung': u'1.0'}, 'alt': ''}}}

tmpfile = tempfile.TemporaryFile()

def pdftest(context):
    createpdf(context, tmpfile, ma, gb, sb, langvar='de')
